from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    MEMBER = "MEMBER"
    GUEST = "GUEST"


class OAuthProvider(str, Enum):
    LOCAL = "local"
    GITHUB = "github"
    GOOGLE = "google"


class OrgRole(str, Enum):
    OWNER = "OWNER"
    ADMIN = "ADMIN"
    PROJECT_MANAGER = "PROJECT_MANAGER"
    DEVELOPER = "DEVELOPER"
    VIEWER = "VIEWER"
    MEMBER = "MEMBER"
    GUEST = "GUEST"


class TeamRole(str, Enum):
    LEAD = "LEAD"
    MEMBER = "MEMBER"


class InvitationStatus(str, Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class AuditAction(str, Enum):
    ORG_CREATED = "ORG_CREATED"
    ORG_UPDATED = "ORG_UPDATED"
    MEMBER_INVITED = "MEMBER_INVITED"
    MEMBER_JOINED = "MEMBER_JOINED"
    ROLE_UPDATED = "ROLE_UPDATED"
    MEMBER_REMOVED = "MEMBER_REMOVED"
    OWNERSHIP_TRANSFERRED = "OWNERSHIP_TRANSFERRED"
    TEAM_CREATED = "TEAM_CREATED"
    TEAM_MEMBER_ADDED = "TEAM_MEMBER_ADDED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_ARCHIVED = "PROJECT_ARCHIVED"
    ISSUE_CREATED = "ISSUE_CREATED"
    ISSUE_UPDATED = "ISSUE_UPDATED"
    ISSUE_STATUS_CHANGED = "ISSUE_STATUS_CHANGED"
    ISSUE_PRIORITY_CHANGED = "ISSUE_PRIORITY_CHANGED"
    ISSUE_ASSIGNED = "ISSUE_ASSIGNED"
    ISSUE_ARCHIVED = "ISSUE_ARCHIVED"
    ISSUE_RESTORED = "ISSUE_RESTORED"
    COMMENT_CREATED = "COMMENT_CREATED"
    COMMENT_UPDATED = "COMMENT_UPDATED"
    COMMENT_DELETED = "COMMENT_DELETED"


class ProjectRole(str, Enum):
    LEAD = "LEAD"
    MAINTAINER = "MAINTAINER"
    CONTRIBUTOR = "CONTRIBUTOR"
    VIEWER = "VIEWER"


class ProjectTemplateType(str, Enum):
    KANBAN = "KANBAN"
    SCRUM = "SCRUM"
    BUG_TRACKING = "BUG_TRACKING"
    ROADMAP = "ROADMAP"
    CUSTOM = "CUSTOM"


class IssueStatus(str, Enum):
    BACKLOG = "BACKLOG"
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    IN_REVIEW = "IN_REVIEW"
    DONE = "DONE"
    CANCELLED = "CANCELLED"


class IssuePriority(str, Enum):
    NO_PRIORITY = "NO_PRIORITY"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"

